### PR TITLE
v0.10.8b0

### PR DESCRIPTION
**Pull request by Zeitsperre**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Zeitsperre** [comment]
@huard With this PR, both PyPI and conda packages will be up to date with yesterday's build.

**Comment by huard** [comment]
Was it outdated ? Do we want to publish every patch ? That seems over the top. I suggest we publish every minor tag (every month or so).

**Comment by Zeitsperre** [comment]
The previous patch was v0.10.6b0 so I figured I'd send along .7 and .8. Would you be OK with publishing every minor patch after v1.0? I feel like we're still building key components into our patches that Finch and users could benefit from.

**Comment by tlvu** [comment]
Just for my info, so PyPI publishing is automated by Travis each time we tag.  But Conda publishing is a manual process?

**Comment by huard** [comment]
In principle, each key component that we add would generate a minor release. I suggest we release patches that we know have downstream implications, on our notebooks for example.

**Comment by tlvu** [comment]
If all publishing are automated, then we do not have to worry about which tag is worth to publish.  If conda publishing model is designed like this (manual PR each time) of course we can not do anything much.  I was simply curious if the publishing process is by design over manual PR, not saying we have to automate it fully right now.

**Pull request merged**
